### ISSUE TITLE
rare NPE on core service startup, puts ServiceHost in zombie state

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [dCentralizedSystems/core#20]
[0][I][2020-06-11T01:25:07.958Z][1][8000][startImpl][ServiceHost/a8892605(LCR24ZS0-627497520bc5e5848) listening on http://192.168.50.10:8000]
[1][I][2020-06-11T01:25:07.968Z][1][8000][start][com.dcentralized.cap.applications.MobileRobotRaspberryPiHost/5bb45bc1 started service host]
[3][I][2020-06-11T01:25:09.119Z][22][8000][setupUser][User stream-source@dcentralized.com already exists, skipping setup of user]
[2][I][2020-06-11T01:25:09.119Z][21][8000][setupUser][User operator@lcr already exists, skipping setup of user]
[4][W][2020-06-11T01:25:09.269Z][14][Utils][logWarning][Uncaught failure inside completion: java.lang.NullPointerException
	at com.dcentralized.core.common.StatefulService.lambda$processCompletionStageReplicationProposal$4(StatefulService.java:953)
	at com.dcentralized.core.common.Operation.lambda$nestCompletion$1(Operation.java:1467)
	at com.dcentralized.core.common.Operation.completeOrFail(Operation.java:1436)
	at com.dcentralized.core.common.Operation.complete(Operation.java:1282)
	at com.dcentralized.core.services.common.NodeSelectorReplicationService.replicateUpdate(NodeSelectorReplicationService.java:77)
	at com.dcentralized.core.services.common.ConsistentHashingNodeSelectorService.replicateRequest(ConsistentHashingNodeSelectorService.java:534)
	at com.dcentralized.core.services.common.ConsistentHashingNodeSelectorService.selectAndForward(ConsistentHashingNodeSelectorService.java:350)
	at com.dcentralized.core.services.common.ConsistentHashingNodeSelectorService.selectAndForward(ConsistentHashingNodeSelectorService.java:315)
	at com.dcentralized.core.common.ServiceHost.replicateRequest(ServiceHost.java:5161)
	at com.dcentralized.core.common.StatefulService.processCompletionStageReplicationProposal(StatefulService.java:957)
	at com.dcentralized.core.common.StatefulService.handleRequestCompletion(StatefulService.java:842)
	at com.dcentralized.core.common.Operation.lambda$nestCompletion$1(Operation.java:1467)
	at com.dcentralized.core.common.Operation.completeOrFail(Operation.java:1436)
	at com.dcentralized.core.common.Operation.complete(Operation.java:1282)
	at com.dcentralized.core.services.common.AuthCredentialsService.handlePatch(AuthCredentialsService.java:116)
	at com.dcentralized.core.common.StatefulService.handleRequestStageExecutingServiceHandler(StatefulService.java:477)
	at com.dcentralized.core.common.StatefulService.handleRequest(StatefulService.java:432)
	at com.dcentralized.core.common.StatefulService.lambda$loadAndLinkState$8(StatefulService.java:1238)
	at com.dcentralized.core.common.Operation.lambda$nestCompletion$1(Operation.java:1467)
	at com.dcentralized.core.common.Operation.completeOrFail(Operation.java:1436)
	at com.dcentralized.core.common.Operation.complete(Operation.java:1282)
	at com.dcentralized.core.common.ServiceHost.loadServiceState(ServiceHost.java:3280)
	at com.dcentralized.core.common.StatefulService.loadAndLinkState(StatefulService.java:1240)
	at com.dcentralized.core.common.StatefulService.handleRequestLoadingAndLinkingState(StatefulService.java:522)
	at com.dcentralized.core.common.StatefulService.handleRequest(StatefulService.java:392)
	at com.dcentralized.core.common.StatefulService.handleRequest(StatefulService.java:356)
	at com.dcentralized.core.common.ServiceHost.executeOperationHandler(ServiceHost.java:3805)
	at com.dcentralized.core.common.ServiceHost.lambda$queueOrScheduleRequestInternal$28(ServiceHost.java:3796)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
]

**Comment by georgechrysanthakopoulos** [comment]
the code in question can not cause an NPE. this is a JIT or compiler bug. very weird. the capture "op" variable is null. but it was obviously NOT null for the completion to trigger on that same operation instance. we have seen this once before
